name: win-build

on:
  push:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  winbuild:
    name: Compile
    runs-on: windows-2022
    strategy:
      matrix:
        target-cpu: [x64]
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0
    steps:
    - name: Download Windows SDK Setup 10.0.20348
      shell: cmd
      run: curl -Lo winsdksetup.exe https://go.microsoft.com/fwlink/?linkid=2164145
    - name: Install Debugging Tools for Windows
      id: windbg
      shell: cmd
      run: |
        setlocal enabledelayedexpansion
        start /WAIT %CD%\winsdksetup.exe /features OptionId.WindowsDesktopDebuggers /q /log %CD%\log.txt
        echo ::set-output name=ERRORLEVEL::!ERRORLEVEL!
    - name: Print Log
      if: always()
      shell: cmd
      run: |
        type log.txt
        exit /b ${{ steps.windbg.outputs.ERRORLEVEL }}
    - name: Download Depot Tools
      shell: cmd
      run: curl -o depot_tools.zip https://storage.googleapis.com/chrome-infra/depot_tools.zip
    - name: Extract Depot Tools
      shell: cmd
      run: |
        mkdir depot_tools
        cd depot_tools
        7z x ..\depot_tools.zip
    - name: Initialize Depot Tools
      shell: cmd
      run: |
        cd depot_tools
        gclient
        exit /b 0
    - name: Prepend Depot Tools to PATH
      shell: cmd
      run: |
        cd depot_tools
        set /p="%CD%" < nul >> %GITHUB_PATH%
        exit /b 0
    - name: Clone ANGLE
      shell: cmd
      run: mkdir angle && cd angle && fetch angle && gclient sync
    - name: Configure ANGLE
      shell: cmd
      env:
        ANGLE_TARGET_CPU: ${{ matrix.target-cpu }}
      run: cd angle && gn gen out/Release --args="target_cpu = \"%ANGLE_TARGET_CPU%\" is_debug = false is_component_build = false"
    - name: Build
      shell: cmd
      run: cd angle && autoninja -C out/Release
    - name: Artifact Preparation
      shell: cmd
      run: |
        mkdir output
        xcopy angle\out output /e /I /d /h /r /y
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: angle-${{ matrix.target-cpu }}
        path: output/
